DO $$ BEGIN
 CREATE TYPE "public"."capstone_program_status" AS ENUM('submissions', 'matching', 'active', 'ending', 'archived', 'hidden');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."capstone_project_log_type" AS ENUM('submission', 'deferment', 'approval', 'partner_message', 'instructor_admin_message', 'course_transfer');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."capstone_project_status" AS ENUM('draft', 'submitted', 'deferred', 'active', 'archived', 'incomplete');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."season" AS ENUM('winter', 'spring', 'summer', 'fall');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."sequence_type" AS ENUM('iterated', 'repeated');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."user_type" AS ENUM('project_partner', 'student', 'instructor', 'admin');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_instructors" (
	"program_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	CONSTRAINT "capstone-portal-project_instructors_program_id_user_id_pk" PRIMARY KEY("program_id","user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_programs" (
	"program_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_programs_program_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"program_name" varchar(256) NOT NULL,
	"program_description" text,
	"program_status" "capstone_program_status" NOT NULL,
	"start_term_id" integer NOT NULL,
	"end_term_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_project_log" (
	"project_log_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_project_log_project_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"date_created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"content" text,
	"memo" text,
	"user_id" integer NOT NULL,
	"project_log_type" "capstone_project_log_type" NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_project_tags" (
	"project_tag_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_project_tags_project_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"capstone" integer NOT NULL,
	"tag_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_projects" (
	"project_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_projects_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"programs_id" integer NOT NULL,
	"project_title" varchar(256) NOT NULL,
	"app_image" varchar(512) DEFAULT '',
	"app_video" varchar(512) DEFAULT '',
	"app_organization" varchar(512) NOT NULL,
	"app_description" text NOT NULL,
	"app_objectives" text NOT NULL,
	"app_motivations" text NOT NULL,
	"app_min_qualifications" text NOT NULL,
	"app_pref_qualifications" text NOT NULL,
	"showcase_description" text,
	"showcase_image" varchar(512),
	"showcase_video" varchar(512),
	"is_showcase_published" boolean,
	"sequence_id" integer,
	"sequence_report" text,
	"project_github_link" varchar(512)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_saved_projects" (
	"save_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_saved_projects_save_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"save_index" integer NOT NULL,
	"preference_description" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_sequences" (
	"sequence_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_sequences_sequence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "sequence_type",
	"description" text,
	"show_reports_to_student" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_tags" (
	"tag_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_tags_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tag" varchar(256)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_teams" (
	"team_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_teams_team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"capacity" integer,
	"date_created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"date_updated" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_term" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_term_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"season" "season" NOT NULL,
	"year" integer NOT NULL,
	"is_published" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_users" (
	"user_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_users_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"date_created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"type" "user_type",
	"program_id" integer,
	"ranking_submitted" boolean NOT NULL,
	"team_id" integer
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_instructors" ADD CONSTRAINT "capstone-portal-project_instructors_program_id_capstone-portal-project_programs_program_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."capstone-portal-project_programs"("program_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_instructors" ADD CONSTRAINT "capstone-portal-project_instructors_user_id_capstone-portal-project_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."capstone-portal-project_users"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_programs" ADD CONSTRAINT "capstone-portal-project_programs_start_term_id_capstone-portal-project_term_id_fk" FOREIGN KEY ("start_term_id") REFERENCES "public"."capstone-portal-project_term"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_programs" ADD CONSTRAINT "capstone-portal-project_programs_end_term_id_capstone-portal-project_term_id_fk" FOREIGN KEY ("end_term_id") REFERENCES "public"."capstone-portal-project_term"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_project_log" ADD CONSTRAINT "capstone-portal-project_project_log_project_id_capstone-portal-project_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."capstone-portal-project_projects"("project_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_project_log" ADD CONSTRAINT "capstone-portal-project_project_log_user_id_capstone-portal-project_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."capstone-portal-project_users"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_project_tags" ADD CONSTRAINT "capstone-portal-project_project_tags_capstone_capstone-portal-project_projects_project_id_fk" FOREIGN KEY ("capstone") REFERENCES "public"."capstone-portal-project_projects"("project_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_project_tags" ADD CONSTRAINT "capstone-portal-project_project_tags_tag_id_capstone-portal-project_tags_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."capstone-portal-project_tags"("tag_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_projects" ADD CONSTRAINT "capstone-portal-project_projects_programs_id_capstone-portal-project_programs_program_id_fk" FOREIGN KEY ("programs_id") REFERENCES "public"."capstone-portal-project_programs"("program_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_projects" ADD CONSTRAINT "capstone-portal-project_projects_sequence_id_capstone-portal-project_sequences_sequence_id_fk" FOREIGN KEY ("sequence_id") REFERENCES "public"."capstone-portal-project_sequences"("sequence_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_saved_projects" ADD CONSTRAINT "capstone-portal-project_saved_projects_user_id_capstone-portal-project_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."capstone-portal-project_users"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_saved_projects" ADD CONSTRAINT "capstone-portal-project_saved_projects_project_id_capstone-portal-project_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."capstone-portal-project_projects"("project_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_teams" ADD CONSTRAINT "capstone-portal-project_teams_project_id_capstone-portal-project_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."capstone-portal-project_projects"("project_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_users" ADD CONSTRAINT "capstone-portal-project_users_program_id_capstone-portal-project_programs_program_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."capstone-portal-project_programs"("program_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_users" ADD CONSTRAINT "capstone-portal-project_users_team_id_capstone-portal-project_teams_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."capstone-portal-project_teams"("team_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
