CREATE TABLE IF NOT EXISTS "capstone-portal-project_capstone_project" (
	"cp_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_capstone_project_cp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_id" integer NOT NULL,
	"cp_title" varchar(256) NOT NULL,
	"cp_description" text,
	"cp_objectives" text,
	"cp_date_created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"cp_date_updated" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"cp_archived" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_course" (
	"course_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_course_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"u_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"term" varchar(256) NOT NULL,
	"course_description" text,
	"is_archived" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_review" (
	"review_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_review_review_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"u_id" integer NOT NULL,
	"rating" real NOT NULL,
	"comments" text,
	"date_created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_saved_project" (
	"save_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_saved_project_save_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"u_id" integer NOT NULL,
	"cp_id" integer NOT NULL,
	"date_saved" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "capstone-portal-project_users" (
	"u_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_users_u_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"u_name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_capstone_project" ADD CONSTRAINT "capstone-portal-project_capstone_project_course_id_capstone-portal-project_course_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."capstone-portal-project_course"("course_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_course" ADD CONSTRAINT "capstone-portal-project_course_u_id_capstone-portal-project_users_u_id_fk" FOREIGN KEY ("u_id") REFERENCES "public"."capstone-portal-project_users"("u_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_review" ADD CONSTRAINT "capstone-portal-project_review_u_id_capstone-portal-project_users_u_id_fk" FOREIGN KEY ("u_id") REFERENCES "public"."capstone-portal-project_users"("u_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_saved_project" ADD CONSTRAINT "capstone-portal-project_saved_project_u_id_capstone-portal-project_users_u_id_fk" FOREIGN KEY ("u_id") REFERENCES "public"."capstone-portal-project_users"("u_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_saved_project" ADD CONSTRAINT "capstone-portal-project_saved_project_cp_id_capstone-portal-project_capstone_project_cp_id_fk" FOREIGN KEY ("cp_id") REFERENCES "public"."capstone-portal-project_capstone_project"("cp_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
