CREATE TABLE IF NOT EXISTS "capstone-portal-project_homepage_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capstone-portal-project_homepage_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hero_title" varchar(256) NOT NULL,
	"hero_subtitle" varchar(256) NOT NULL,
	"main_content" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "capstone-portal-project_programs" ADD COLUMN "clerk_organization_id" varchar(256);--> statement-breakpoint
ALTER TABLE "capstone-portal-project_users" ADD COLUMN "project_id" integer;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "capstone-portal-project_users" ADD CONSTRAINT "capstone-portal-project_users_project_id_capstone-portal-project_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."capstone-portal-project_projects"("project_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
